### ISSUE TITLE
Graceful 404s & error boundaries

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/design-system#14]
### Context

> We should maybe add an issue to handle 404s gracefully in the site with a default route and an error boundary or two. 

> Might also want to think architecturally about how we want to handle UI error/status messages generally. Do we want a toast component or popup? Or should we add an error message slot to the form components so that forms handle request status? Lots of good options, but when we sync on the roadmap, that may be something to discuss.

- @joshuagraber 

### Requirements

- [ ] Establish a global error handling strategy that includes capturing, logging, and displaying errors gracefully.
   - [ ] forms: we should tell people what's up with their form, if it's incorrect
   - [x] search: we should use a persistent error message clarify _why_ there are sometimes 0 matching results (if the search failed somehow vs. there are actually 0 results and they should `request data`)
- [ ] Develop a generic 404 view component that can serve as an error boundary.
   - I would prefer we not get too `cute` with error messages—we should be as informative as possible (including "we don't know what went wrong") and not funny about how a bunch of kittens are playing in our wires like yarn. or whatever

### Docs

- [ ] Document the integration process for the error handling components, ensuring it's adaptable for future microservices.

**Comment by joshuagraber** [comment]
@josh-chamberlain This all looks really good, thank you for the guidance here.

A couple thoughts:
> search: we should use a persistent error message clarify why there are sometimes 0 matching results (if the search failed somehow vs. there are actually 0 results and they should request data)

I actually think error parsing is best left to the calling application. The components shouldn't have to know that info, just to accept error message and render. Since different apps could be using, I think the props should be as generic as possible.

> notification: in the not-too-distant future, we will want to be able to show notifications to users (related to data requests/updated sources matching queries/etc.) 

Love this, looking forward to developing. I assume the part that will be handled here will be UI components, and the actual service will be handled by a backend, yes?

**Comment by josh-chamberlain** [comment]
@joshuagraber both comments make sense to me, as long as my intent was clear I think we're good! feel free to edit my comment if need be

**Comment by mbodeantor** [comment]
Here is a summary of the current endpoint response codes:

> QuickSearch and SearchTokens wrapper for it:

>>200: results (or no results)
>>500: "There was an error during the search operation"

>DataSourceById:
>>200: results
>>404: "Data source not found

PR to update User and other DataSource endpoint to use 500s for errors:
https://github.com/Police-Data-Accessibility-Project/data-sources-app/pull/201

**Comment by mbodeantor** [comment]
That PR will also have QuickSearch return a 404 when there are no results and a message "No results found. Please considering requesting a new data source."

**Comment by josh-chamberlain** [comment]
@mbodeantor looks like this one is safe to close?
