### ISSUE TITLE
Button component styles are overridden by user agent in some browsers

### ISSUE THREAD

**Issue by joshuagraber** [Police-Data-Accessibility-Project/design-system#19]
When `type="submit"` is added to one of our `Button` components, user agent styles override our background styles with a transparent in Firefox and Chrome.

<img width="466" alt="Screenshot 2023-11-29 at 11 44 01 AM" src="https://github.com/Police-Data-Accessibility-Project/design-system/assets/68428039/a79b1517-6d77-4f70-ac95-2c1eecfe7062">

**Comment by josh-chamberlain** [comment]
referencing [this TODO in the code](https://github.com/Police-Data-Accessibility-Project/data-sources-app/pull/123/files#diff-ecdb84b8617d5229ab0f8338eab22ddbfcfd993c52796b7d05605245e82428f4R70)
