### ISSUE TITLE
Export eslint config for use in other client apps

### ISSUE THREAD

**Issue by joshuagraber** [Police-Data-Accessibility-Project/design-system#40]
Follow the pattern established the `/config` directory, from which we currently export the `TailwindCSS` config. 

The `design-system` config itself is designed for typescript, so this will be a two-part project.

- [x] Create an `eslint-config` directory and create a sub-package `@pdap-design-system/eslint-config`.
- [x] Export the base config from this package. This will bundle the config as a part of the package, for use in other projects.
- [x] In the root directory, update `eslintrc.json` -> `eslintrc.cjs` and extend the base config from `@pdap-design-system/eslint-config`.
- [x] Update the `README` to ensure ease of use.

**Comment by Kenny4297** [comment]
Hi @joshuagraber, I believe that I can help with this issue. Would you mind assigning me to it?

**Comment by Kenny4297** [comment]
Hi @joshuagraber. Your code looks good! A few clarification questions:

1) Did you end up updating the eslintrc.json to eslintrc.js? I don't see this change in your current PR; am I missing something?

2) When I update the README, do you want me to assume / include that you have in fact published the the config package to npm?

Any assistance would be helpful!

**Comment by joshuagraber** [comment]
Hey, @Kenny4297 thank you for the clarifying questions here.

1. Yes, but `eslint` was complaining that it wasn't able to import it via dynamic `require` (perhaps they went `cjs`-only in version 8? I haven't had the chance to look into it), so I renamed to `eslintrc.cjs` to allow for the `commonjs` methods that `eslint` is expecting. The file is [here](https://github.com/Police-Data-Accessibility-Project/design-system/pull/44/files#diff-e1ce717e1179a0db14e90ec5374768a206651ca807db58352991eb7895ed7c9c). I've updated the issue description to match.

2. Yes, please! in `eslint-config/package.json`, you'll see that the `"name"` value is `"@pdap-design-system/eslint-config`. This will be extendable using the same string, once published (and we will publish before we merge this PR). So, TLDR: yes.

And then, if you are interested in picking up any other issues, [this one is related](https://github.com/Police-Data-Accessibility-Project/pdap.io/issues/167) and may be a good next step.
