### ISSUE TITLE
Update release workflow to include a beta release strategy

### ISSUE THREAD

**Issue by joshuagraber** [Police-Data-Accessibility-Project/design-system#60]
As a part of the [search v2](https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/248) work, there will be a lot of updates to this repo. We would like to release frequently to test these updates without disturbing the `main` branch or production release flow.

- [x] Create `beta` branch in git
- [x] Modify `release` workflow and `semantic-release` config to support this.
- [x] Test by releasing a "beta" release that matches the current prod release

**Comment by joshuagraber** [comment]
@josh-chamberlain Marking this as complete. See [releases](https://github.com/Police-Data-Accessibility-Project/design-system/releases) to see beta release published using new config.

For anything large that is likely to cause a breaking change, we can now merge to the `beta` branch to pre-release and test without symlinking.

**Comment by josh-chamberlain** [comment]
nice, this is great! we should use this as a model for API / other versions down the road
