### ISSUE TITLE
Create loading spinner / shimmer

### ISSUE THREAD

**Issue by joshuagraber** [Police-Data-Accessibility-Project/design-system#63]
As a part of the [search v2](https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/248) work, we want both a loading spinner and a shimmer effect 

- [ ] Create a loading spinner component (use an SVG)
- [ ] Create a shimmer component (just a div with animation classes applied)
- [ ] Write tests to cover new components
- [ ] Update documentation
- [ ] Raise PR against `beta`

**Comment by josh-chamberlain** [comment]
does this include "Subtle transition animations for [routes](https://router.vuejs.org/guide/advanced/transitions.html) and [elements](https://vuejs.org/guide/extras/animation.html) entering / exiting the DOM"?

**Comment by joshuagraber** [comment]
@josh-chamberlain No, that's more an app-level thing. Just like a little fade-in when the route changes, of fading in and out of loading states, or a slide down when the dropdown opens. Little things like that that make the UI feel slick. Tailwind and Vue both have some nice, easy options for transitions/animations, so if we're rebuilding things anyways, I'd be interested in making some of those enhancements along the way.
